<?php require('template/header.phtml') ?>

    <div class="header">
        <h2>Admin</h2>
    </div>

    <form method="post" action="create_user.php">

<!--         echo $display_error();-->
        <div class="form-group">
            <label for="username" class="cols-sm-2 control-label">Username</label>
            <div class="cols-sm-10">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" name="u_name" id="u_name"  placeholder="Enter your Username" />
                    <?php echo "<p class='text-danger'>$nameError</p>";?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="email" class="cols-sm-2 control-label">Email Adress</label>
            <div class="cols-sm-10">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                    <input type="email" class="form-control" name="u_email" id="u_email"  placeholder="Email Address" />
                    <?php echo "<p class='text-danger'>$emailError</p>";?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label>User type</label>
            <select name="user_type" id="user_type" >
                <option value=""></option>
                <option value="admin">Admin</option>
                <option value="user">User</option>
            </select>
        </div>

        <div class="form-group">
            <label for="password" class="cols-sm-2 control-label">Password</label>
            <div class="cols-sm-10">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                    <input type="password" class="form-control" name="u_password" id="u_password"  placeholder="Enter your Password" />
                    <?php echo "<p class='text-danger'>$password1Error</p>";?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="confirm" class="cols-sm-2 control-label">Confirm Password</label>
            <div class="cols-sm-10">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                    <input type="password" class="form-control" name="u_cpassword" id="u_cpassword"  placeholder="Confirm your Password" />
                    <?php echo "<p class='text-danger'>$password2Error</p>";?>
                </div>
            </div>
        </div>

        <div class="input-group">
            <button type="submit" class="btn" name="register_btn"> Login </button>
        </div>
    </form>
    </body>
    </html>

<?php require('template/footer.phtml') ?>