<?php require('template/header.phtml') ?>
    <h3> Login Page </h3>


    <form class="form-horizontal" role="form" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
        <div>
            <a href="register.php">Don't have an account! Register here!</a>
        </div>
        <br/>
        <div class="form-group">
            <label for="user" class="col-sm-2 control-label"> Username: </label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="u_name" name="u_name" placeholder="enter username..."
                       value="">
                <?php echo "<p class='text-danger'>$usernameError</p>"; ?>
            </div>
        </div>

        <div class="form-group">
            <label for="pass" class="col-sm-2 control-label"> Password: </label>
            <div class="col-sm-4">
                <input type="password" class="form-control" id="u_password" name="u_password"
                       placeholder="enter password..." value="">
                <?php echo "<p class='text-danger'>$passwordError</p>"; ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="capcha">
                    <label><input value="" name="cap" type="text"> Enter the Capcha </label>
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <input id="submit" name="login" type="submit" value="Login" class="btn btn-success">

                <input id="reset" name="reset" type="reset" value="Reset" class="btn btn-danger">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label><input value="check" name="check" type="checkbox"> Remember me? </label>
                </div>
            </div>
        </div>
    </form>


    <p><?php echo $view->login ?></p>

<?php require('template/footer.phtml') ?>